import { Component } from '@angular/core';

export interface Section {
  name: string;  
}

@Component({
  selector: 'app-catalog',
  templateUrl: './catalog.component.html',
  styleUrls: ['./catalog.component.css']
})
export class CatalogComponent {
 
  products: Section[] = [
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    {name: 'Photos'},
    
  ];  
}
